dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
notifications:
  email:
    recipients:
      - paul.bavazzano@gmail.com
      - elkhantache.ismael@gmail.com
      - ceuterickx.gaetan@gmail.com
    on_success: always
    on_failure: always

# install:
#   - pip install -r requirements.txt
#   - pip install .

# script:
#   - python -m tests.BasicTestModel
  # - sonar-scanner

addons:
  sonarcloud:
    organization: "fourmipanda-github"
    token:
      secure: "56bce8dff72259a035befdac40f0a88a9d2d04e3"